/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATHOPERATIONS_H_RPCGEN
#define _MATHOPERATIONS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MATHOPERATIONS_PROG 0x31111111
#define MATHOPERATIONS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define prepara_primer_digito 1
extern  int * prepara_primer_digito_1(int *, CLIENT *);
extern  int * prepara_primer_digito_1_svc(int *, struct svc_req *);
#define prepara_segundo_digito 2
extern  int * prepara_segundo_digito_1(int *, CLIENT *);
extern  int * prepara_segundo_digito_1_svc(int *, struct svc_req *);
#define suma_remota 3
extern  int * suma_remota_1(void *, CLIENT *);
extern  int * suma_remota_1_svc(void *, struct svc_req *);
#define resta_remota 4
extern  int * resta_remota_1(void *, CLIENT *);
extern  int * resta_remota_1_svc(void *, struct svc_req *);
#define multiplicacion_remota 5
extern  int * multiplicacion_remota_1(void *, CLIENT *);
extern  int * multiplicacion_remota_1_svc(void *, struct svc_req *);
#define division_remota 6
extern  int * division_remota_1(void *, CLIENT *);
extern  int * division_remota_1_svc(void *, struct svc_req *);
extern int mathoperations_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define prepara_primer_digito 1
extern  int * prepara_primer_digito_1();
extern  int * prepara_primer_digito_1_svc();
#define prepara_segundo_digito 2
extern  int * prepara_segundo_digito_1();
extern  int * prepara_segundo_digito_1_svc();
#define suma_remota 3
extern  int * suma_remota_1();
extern  int * suma_remota_1_svc();
#define resta_remota 4
extern  int * resta_remota_1();
extern  int * resta_remota_1_svc();
#define multiplicacion_remota 5
extern  int * multiplicacion_remota_1();
extern  int * multiplicacion_remota_1_svc();
#define division_remota 6
extern  int * division_remota_1();
extern  int * division_remota_1_svc();
extern int mathoperations_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATHOPERATIONS_H_RPCGEN */
