/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mathoperations.h"
#include <stdlib.h>
int  prepara_primer_digito_1_arg = 0;
int  prepara_segundo_digito_1_arg = 0;
void
mathoperations_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  *result_2;
	int  *result_3;
	char *suma_remota_1_arg = "s";
	int  *result_4;
	char *resta_remota_1_arg = "f";
	int  *result_5;
	char *multiplicacion_remota_1_arg = "f";
	int  *result_6;
	char *division_remota_1_arg = "f";

#ifndef	DEBUG
	clnt = clnt_create (host, MATHOPERATIONS_PROG, MATHOPERATIONS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = prepara_primer_digito_1(&prepara_primer_digito_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nSe preparó el primer digito\n");
	result_2 = prepara_segundo_digito_1(&prepara_segundo_digito_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nSe preparó el segundo digito\n");

	result_3 = suma_remota_1((void*)&suma_remota_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nEl resultado de la suma es: %i\n", *result_3);
	result_4 = resta_remota_1((void*)&resta_remota_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nEl resultado de la resta es: %i\n", *result_4);
	result_5 = multiplicacion_remota_1((void*)&multiplicacion_remota_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nEl resultado de la multiplicación es: %i\n", *result_5);

	result_6 = division_remota_1((void*)&division_remota_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nEl resultado de la división es: %i\n", *result_6);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prepara_primer_digito_1_arg = atoi(argv[2]);
	prepara_segundo_digito_1_arg = atoi(argv[3]);
	mathoperations_prog_1 (host);
exit (0);
}
